### ISSUE TITLE
Index does not get updated when saving a model

### ISSUE THREAD

**Issue by MarkejN** [MetaModels/attribute_levenshtein#9]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_levensthein/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    8.3.12      |                                  |
| Contao version:                     |    4.13.50      |                                  |
| MetaModels version:                 |    dev-release/2.3.0      |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |    28      |                                  |

## Issue description

The levenshtein index does not get updated in my installation when saving a model. I noticed two issues:

1. The checksum in `WordList` is calculated based on the relevance and not on the words (e.g. `sha1(11)`). If the number of words does not change, the checksum will be correct, even if the words have changed: https://github.com/MetaModels/attribute_levenshtein/blob/4c150750c2107f9348b1bd612ef4796e24742569/src/Attribute/WordList.php#L70
2. Somehow `$metaModel->getActiveLanguage()` returns `en`, although the MetaModel is not translated and the locale in the backend is `de`. I only need and use German. When words are added after saving, they are saved for `en` and not for `de`. https://github.com/MetaModels/attribute_levenshtein/blob/4c150750c2107f9348b1bd612ef4796e24742569/src/Attribute/AttributeLevenshtein.php#L192-L197

## Steps to reproduce

1. Open a model that is already indexed and change one of the words, without changing the number of words.
2. Search for the new word in the frontend.
3. The result is empty.
4. Manually regenerate the search index in the backend.
5. The result is displayed.

## Describe the behaviour of the application

The result is empty.

## Describe the expected behaviour of the application

The model with the word should be displayed.

## Screenshots

Table `tl_metamodel_levensthein` with the checksums `sha1(11)`, `sha1(111)`, ... and language `en`:

![image](https://github.com/user-attachments/assets/915d16b0-9b76-410a-ac51-51c69adb4bc0)

**Comment by zonky2** [comment]
I add at longtext a new word "esdtztr" and save this item - the item has been found with "esdtztr"...

I change the word to "eXdtztr" - the item has been also found

Checked in MM 2.3
